service: view-spot-finder

frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  stage: prod

functions:
  viewSpotFinder:
    handler: handler.viewSpotFinder

plugins:
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'