service: view-spot-finder

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  viewSpotFinder:
    handler: handler.viewSpotFinder

plugins:
  - serverless-plugin-typescript
